services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cruise_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,travelinstyle.lu
    networks:
      - cruise-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cruise_frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - cruise-network

  db:
    image: postgres:14
    container_name: cruise_db
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: cruise_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
      
networks:
  cruise-network:

volumes:
  postgres_data:
